<font size="5" color="white">NumPy Mathematical [41 exercises with solution]</font>

1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2 ,3])

arradd = arr + 5
arrsub = arr - (-3) 
arrmul = arr * 4
arrdiv = arr / 0.25

print(arradd)
print(arrsub)
print(arrmul)
print(arrdiv)

[6 7 8]
[4 5 6]
[ 4  8 12]
[ 4.  8. 12.]


2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.


In [3]:
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)

print(np.logaddexp(l1, l2))
print(np.logaddexp2(l1, l2))

-113.87649168120691
-113.59955522772194


3. Write a NumPy program to get true division of the element-wise array inputs.


In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.


In [7]:
arr = np.array([1.0, 2.0, 3.0, 4.0])

np.floor_divide(arr, 1.5)

array([0., 1., 2., 2.])

5. Write a NumPy program to get the powers of an array values element-wise.


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])

np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216])

6. Write a NumPy program to get the element-wise remainder of an array of division.


In [10]:
arr = np.arange(7)

np.remainder(arr, 5)

array([0, 1, 2, 3, 4, 0, 1])

7. Write a NumPy program to calculate the absolute value element-wise.


In [11]:
arr = np.array([ -10.2, 122.2, 0.2])

np.absolute(arr)


array([ 10.2, 122.2,   0.2])

8. Write a NumPy program to round array elements to the given number of decimals.


In [12]:
x = np.round([1.45, 1.50, 1.55])
print(x)

x = np.round([0.28, .50, .64], decimals=1)
print(x)

x = np.round([.5, 1.5, 2.5, 3.5, 4.5])
print(x) 

[1. 2. 2.]
[0.3 0.5 0.6]
[0. 2. 2. 4. 4.]


9. Write a NumPy program to round elements of the array to the nearest integer.


In [16]:
arr = np.array([[-0.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2. ]])

np.rint(arr)

array([[-1., -2., -2.,  0.,  2.,  2.,  2.]])

10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.


In [17]:
arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2. ])

print(np.trunc(arr))
print(np.ceil(arr))
print(np.floor(arr))

[-1. -1. -0.  0.  1.  1.  2.]
[-1. -1. -0.  1.  2.  2.  2.]
[-2. -2. -1.  0.  1.  1.  2.]


11. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.


In [19]:
arr = np.array([[ 0.44349753, 0.81043761, 0.00771825],
[ 0.64004088, 0.86774612, 0.19944667],
[ 0.61520091, 0.24796788, 0.93798297],
[ 0.22156999, 0.61318856, 0.82348994],
[ 0.91324026, 0.13411297, 0.00622696]])

arr2 = np.array([[ 0.73873542, 0.06448186],
[ 0.90974982, 0.06409165],
[ 0.22321268, 0.39147412]])

arr3 = arr2+arr2

arr3

array([[1.47747084, 0.12896372],
       [1.81949964, 0.1281833 ],
       [0.44642536, 0.78294824]])

12. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.


In [22]:
arr1 = np.array([ 1.+2.j, 3.+4.j])

arr2 = np.array([ 5.+6.j, 7.+8.j])

arr3 = np.vdot(arr1, arr2)

arr3


np.complex128(70-8j)

13. Write a NumPy program to create an inner product of two arrays.


In [23]:
x = np.array([[[ 0, 1, 2, 3],
[ 4, 5, 6, 7],
[ 8, 9, 10, 11]],
[[12, 13, 14, 15],
[16, 17, 18, 19],
[20, 21, 22, 23]]])

y = np.array([0, 1, 2, 3])

z = np.inner(x, y)
z

array([[ 14,  38,  62],
       [ 86, 110, 134]])

14. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.


In [25]:
x = np.array([1, 4, 0])
y = np.array([2, 2, 1])

inner = np.inner(x, y)
outer = np.outer(x, y)
cross = np.cross(x, y)

print(inner)
print("-----------")
print(outer)
print("-----------")
print(cross)

10
-----------
[[2 2 1]
 [8 8 4]
 [0 0 0]]
-----------
[ 4 -1 -6]


15. Write a NumPy program to generate a matrix product of two arrays.


In [28]:
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 4], [2, 2]])

pr_mt = np.matmul(x, y)

pr_mt

array([[3, 4],
       [5, 6]])

16. Write a NumPy program to find the roots of the following polynomials.


In [31]:
print(np.roots([1, -2, 1]))
print("---------------------------------------------------------------------")
print(np.roots([1, -12, 10, 7, -10]))

[1. 1.]
---------------------------------------------------------------------
[11.04461946+0.j        -0.8711421 +0.j         0.91326132+0.4531004j
  0.91326132-0.4531004j]


17. Write a NumPy program to compute the following polynomial values.


In [32]:
print(np.polyval([1, -2, 1], 2))
print(np.polyval([1, -12, 10, 7, -10], 3)) 

1
-142


18. Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another.


In [33]:
from numpy.polynomial import polynomial as P

x = (10, 20, 30)
y = (30, 40, 50)

print(P.polyadd(x,y))
print(P.polydiv(x,y))
print(P.polymul(x, y))
print(P.polysub(x, y))

[40. 60. 80.]
(array([0.6]), array([-8., -4.]))
[ 300. 1000. 2200. 2200. 1500.]
[-20. -20. -20.]


19. Write a NumPy program to calculate mean across dimension, in a 2D numpy array.


In [37]:
arr = np.array([[10, 30],
[20, 60]])

print(arr.mean(axis=0))
print(arr.mean(axis=1))

[15. 45.]
[20. 40.]


20. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.


In [40]:
arr = np.arange(101)

print(arr.mean())
print(arr.std())
print(arr.var())

50.0
29.154759474226502
850.0


21. Write a  NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.


In [41]:
angle1 = np.array([ 0., 0.5, 0.70710678, 0.8660254, 1., ])
angle2 = np.array([ 1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01, 6.12323400e-17])
angle3 = np.array([ 0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00, 1.63312394e+16])

print(np.sin(angle1))
print(np.cos(angle2))
print(np.tan(angle3))

[0.         0.47942554 0.64963694 0.76175998 0.84147098]
[0.54030231 0.64785934 0.7602446  0.87758256 1.        ]
[ 0.          0.65138789  1.55740772 -6.14753307 -0.48456903]


22. Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a given array.


In [43]:
x = np.array([-1., 0, 1.])

print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


23. Write a NumPy program to convert angles from radians to degrees for all elements in a given array.


In [46]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

r1 = np.degrees(x)

r2 = np.rad2deg(x)

assert np.array_equiv(r1, r2)

print(r1)
print(r2)

[-180.  -90.   90.  180.]
[-180.  -90.   90.  180.]


24. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.


In [47]:
x = np.array([-180., -90., 90., 180.])

a1 = np.radians(x)

print(a1)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


25. Write a NumPy program to calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent for all elements in a given array.


In [48]:
arr = np.array([-1., 0, 1.])

sin = np.arcsin(arr)
cos = np.arccos(arr)
tan = np.arctan(arr)

print(sin)
print(cos)
print(tan)

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


26. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) of the input, element-wise of a given array.


In [52]:
arr = np.array([ 3.1, 3.5, 4.5, 2.9, -3.1, -3.5, -5.9])

floor = np.floor(arr)
round = np.round(arr)
ceiling = np.ceil(arr)
truncate = np.trunc(arr)

print(floor)
print(round)
print(ceiling)
print(truncate)

[ 3.  3.  4.  2. -4. -4. -6.]
[ 3.  4.  4.  3. -3. -4. -6.]
[ 4.  4.  5.  3. -3. -3. -5.]
[ 3.  3.  4.  2. -3. -3. -5.]


27. Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.


In [53]:
arr = np.array([[1, 2 ,3], [4, 5 ,6]])

sum1 = np.cumsum(arr)
sum2 = np.cumsum(arr, axis=0)
sum3 = np.cumsum(arr, axis=1)

print(sum1)
print(sum2)
print(sum3)

[ 1  3  6 10 15 21]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


28. Write a NumPy program to calculate cumulative product of the elements along a given axis, sum over rows for each of the 3 columns and product over columns for each of the 2 rows of a given 3x3 array.


In [54]:
arr = np.array([[1, 2, 3],
[4, 5, 6]])

print(np.cumprod(arr))
print(np.cumprod(arr, axis=0))
print(np.cumprod(arr, axis=1))



[  1   2   6  24 120 720]
[[ 1  2  3]
 [ 4 10 18]]
[[  1   2   6]
 [  4  20 120]]


29. Write a NumPy program to calculate the difference between neighboring elements, element-wise of a given array.


In [55]:
arr = np.array([1, 3, 5, 7, 0])

print(np.diff(arr))

[ 2  2  2 -7]


30. Write a  NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.


In [56]:
x = np.array([1, 3, 5, 7, 0])

r1 = np.ediff1d(x, to_begin=[0, 0], to_end=[200])

r2 = np.insert(np.append(np.diff(x), 200), 0, [0, 0])

assert np.array_equiv(r1, r2)

print(r2) 

[  0   0   2   2   2  -7 200]


31. Write a NumPy program to compute ex, element-wise of a given array.


In [57]:
arr = np.array([1., 2., 3., 4.])

pro = np.exp(arr)


print(pro)


[ 2.71828183  7.3890561  20.08553692 54.59815003]


32. Write a NumPy program to calculate exp(x) - 1 for all elements in a given array.


In [58]:
arr = np.array([1., 2., 3., 4.])

exp = np.exp(arr)-1

print(exp)

[ 1.71828183  6.3890561  19.08553692 53.59815003]


33. Write a NumPy program to calculate 2p for all elements in a given array.


In [59]:
arr = np.array([1, 2, 3, 4])

r2 =  arr*2

print(r2)

[2 4 6 8]


34. Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.


In [60]:
x = np.array([1, np.e, np.e**2])

print("\nNatural log =", np.log(x))

print("Common log =", np.log10(x))

print("Base 2 log =", np.log2(x)) 



Natural log = [0. 1. 2.]
Common log = [0.         0.43429448 0.86858896]
Base 2 log = [0.         1.44269504 2.88539008]


35. Write a NumPy program to compute the natural logarithm of one plus each element of a given array in floating-point accuracy.


In [61]:
x = np.array([1e-99, 1e-100])

print(np.log1p(x)) 


[1.e-099 1.e-100]


36. Write a NumPy program to check element-wise True/False of a given array where signbit is set.


In [62]:
x = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])

r1 = np.signbit(x)

r2 = x < 0

assert np.array_equiv(r1, r2)

print(r1)


[ True  True  True  True False False False False False]


37. Write a NumPy program to change the sign of a given array to that of a given array, element-wise.


In [63]:
x1 = np.array([-1, 0, 1, 2])

x2 = -2.1
print(np.copysign(x1, x2)) 


[-1. -0. -1. -2.]


38. Write a NumPy program to compute numerical negative value for all elements in a given array.


In [65]:
x = np.array([0, -1, 1, 2])

r2= np.negative(x)

print(r2)

[ 0  1 -1 -2]


39. Write a NumPy program to compute the reciprocal for all elements in a given array.


In [66]:
x = np.array([1., 2., .2, .3])



r1 = np.reciprocal(x)

r2 = 1/x

assert np.array_equal(r1, r2)

print(r1) 


[1.         0.5        5.         3.33333333]


40. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.


In [67]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

r1 = np.power(x, y)

print("Result- x^y:")
print(r1) 


Result- x^y:
[[ 1  4]
 [ 3 16]]


41. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.


In [69]:
x = np.array([1, 3, 5, 0, -1, -7, 0, 5])

r1 = np.sign(x)

r2 = np.copy(x)
r2[r2 > 0] = 1 
r2[r2 < 0] = -1  

assert np.array_equal(r1, r2)

print(r1)


[ 1  1  1  0 -1 -1  0  1]
